service: ingredofit-aws-lambda-function
provider:
  name: aws
  runtime: nodejs10.x
functions:
  githutAccessTokenGenerator:
    handler: handler.githutAccessTokenGenerator
    events:
     - http:
         path: auth/accessToken/generate
         method: post