service: ingredofit-aws-lambda-function
provider:
  name: aws
  runtime: nodejs10.x
functions:
  githubAccessTokenGenerator:
    handler: handler.githubAccessTokenGenerator
    events:
     - http:
         path: auth/accessToken/generate
         method: post
         cors: true