service: ingredofit
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  environment:
    NODE_PATH: "./:/opt/node_modules"
package:
  exclude:
    - .vscode/**
    - publicModules/**
    - mocks/**
    - client/**
    - lib/**
    - README.md
    - .env.development
layers:
  publicModules:
    path: publicModules
functions:
  githubUserLogin:
    handler: api/handler.githubUserLogin
    layers:
      - {Ref: PublicModulesLambdaLayer}
    events:
     - http:
         path: user/login
         method: post
         cors: true
  getSignedUrlForStorage:
    handler: api/handler.getSignedUrlForStorage
    layers:
      - {Ref: PublicModulesLambdaLayer}
    events:
     - http:
         path: file/signedUrl
         method: get
         cors: true